steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - '-t'
      - 'gcr.io/$PROJECT_ID/spotifygpt:$COMMIT_SHA'
      - .
    id: Build Container Image
    options:
      logging: CLOUD_LOGGING_ONLY
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - 'gcr.io/$PROJECT_ID/spotifygpt:$COMMIT_SHA'
    id: Push Image to Container Registry
    options:
      logging: CLOUD_LOGGING_ONLY
  - name: gcr.io/cloud-builders/gcloud
    args:
      - run
      - deploy
      - spotifygpt
      - '--image'
      - 'gcr.io/$PROJECT_ID/spotifygpt:$COMMIT_SHA'
      - '--region'
      - us-central1
      - '--platform'
      - managed
    id: Deploy Container on Google Cloud Run
    options:
      logging: CLOUD_LOGGING_ONLY
images:
  - 'gcr.io/$PROJECT_ID/spotifygpt:$COMMIT_SHA'